apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base

# Версії образів - оновлюються через CI/CD
images:
  - name: auth-service
    newName: ghcr.io/yakubovskiyandrey/auth-service
    newTag: latest
  - name: user-service
    newName: ghcr.io/yakubovskiyandrey/user-service
    newTag: latest
