apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Секрети створюються через скрипт create-secrets.sh
# Цей файл - для документації структури

generatorOptions:
  disableNameSuffixHash: true
