server:
  port: 8888

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/YakubovskiyAndrey/microservice-sample-config-cloud.git"
          default-label: "main"
          skip-ssl-validation: true
          username: "YakubovskiyAndrey"
          password: ${GIT_KEY}