server:
  port: 9091

spring:
  data:
    mongodb:
      # Значення беруться з env variables, fallback для локальної розробки
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      username: ${MONGO_USERNAME:admin}
      password: ${MONGO_PASSWORD:admin}
      database: ${MONGO_DATABASE:UserProfileDB}
      authentication-database: admin