apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Загальний namespace для всіх ресурсів
namespace: cloud-demo

resources:
  # Namespace
  - namespace.yml

  # Інфраструктура (бази даних)
  - postgresql
  - mongodb

  # Сервіси
  - config-server
  - auth
  - user
