server:
  port: 9090

spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:AuthDB}
  jpa:
    hibernate:
      ddl-auto: update

# --- ACTUATOR CONFIGURATION ---
management:
  endpoints:
    web:
      exposure:
        include: health,info  # включаем только нужные эндпоинты
  endpoint:
    health:
      show-details: always     # показываем детали health
  server:
    port: 9090