server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    # Значення беруться з env variables, fallback для локальної розробки
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:AuthDB}
  jpa:
    hibernate:
      ddl-auto: update